# app_secret and access_token_secret are in application.yml
app_key: "wuocfo996wbfqnb"
app_secret: <%= ENV["APP_SECRET"] %>
access_token: "6uqhtofzruag6iet"
access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
user_id: "416768356"
access_type: "app_folder"